export { default as Contact} from './Contact'
export { default as Error} from './Error'
export { default as Home} from './Home'
export { default as Layout} from './Layout'
export { default as Projects} from './Projects'